[placeholders.use_wasi]
type = "bool"
prompt = "Do you want to use WASI? It allows accessing the file system, but it is unstable."
default = false

[placeholders.std_layer]
type = "string"
prompt = "How much of the standard library do you need? (core = no heap allocations, alloc = heap allocations, std = operating system access (mostly only useful with WASI)"
choices = ["core", "alloc", "std"]
default = "core"

[placeholders.toolchain]
type = "string"
prompt = "Which Rust toolchain do you want to use?"
choices = ["stable", "nightly"]
default = "stable"

[placeholders.has_settings]
type = "bool"
prompt = "Does your auto splitter have settings?"
default = false

[placeholders.process_name]
type = "string"
prompt = "What is the name of the game's executable?"
default = "explorer.exe"

[placeholders.platform]
type = "string"
prompt = "Which platform / game engine does the game use?"
choices = ["Neither", "Unity", "Game Boy Advance", "GameCube", "SEGA Genesis", "PlayStation 1", "PlayStation 2", "SEGA Master System / GameGear", "Wii"]
default = "Neither"
